## Scripting Based Questions

### 1.	Write a program to take a name and age from the user and print a greeting message.

In [70]:
user_name=input("Enter your name:")
user_age=int(input("Enter your age:"))

print("Hello {}, Welcome to the course. Please confirm is your age is {}?".format(user_name,user_age))

Enter your name: vijay
Enter your age: 25

Hello vijay, Welcome to the course. Please confirm is your age is 25?

### 2.	Create a list of numbers and print only even numbers using a for loop.

In [71]:
numbers_list=[3,22,321,334,556,75,34,68,222,1234,55,57,89,97]
for i in range(0,len(numbers_list)):
    if numbers_list[i]%2==0:
        print("{} is a even number".format(numbers_list[i]))

22 is a even number
334 is a even number
556 is a even number
34 is a even number
68 is a even number
222 is a even number
1234 is a even number

### 3.	Write a program that handles division by zero using try-except.

In [10]:
divident=int(input("Enter the divident"))
divisor=int(input("Enter the divisor"))

try:
    print(divident/divisor)
except ZeroDivisionError:
    print("Invalid number!, Enter a valid number")

Enter the divident 3
Enter the divisor 9

0.3333333333333333

### 4.	Given a string, count how many vowels it has.

In [72]:
string= "Hi I am Vigneshwar"
count=0
for vowels in string:
    if vowels.lower() in 'aeiou':
        print(vowels)
        count+=1
print("Total vowels count is {}".format(count))

i
I
a
i
e
a
Total vowels count is 6

### 5.	Reverse a list without using built-in functions.

In [73]:
list1=[1,2,3,4,5]
list2=[]
for value in reversed(list1):
    list2.append(value)
print(list2)

[5, 4, 3, 2, 1]

### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [9]:
Education_details={"Roll no":[11,12,13,14,15,16],
                  "Name":["Sanjani","Vigneshwar","Kanimozhi","Arivazhagan","Priya","Adhikesvan"],
                  "Education":["B.E","B.E","M.com","Diploma","B.com","M.ED"],
                  "Percentage":[90,80,95,75,95,75],
                  "Age":[25,25,51,62,48,51]}
print(Education_details)

{'Roll no': [11, 12, 13, 14, 15, 16], 'Name': ['Sanjani', 'Vigneshwar', 'Kanimozhi', 'Arivazhagan', 'Priya', 'Adhikesvan'], 'Education': ['B.E', 'B.E', 'M.com', 'Diploma', 'B.com', 'M.ED'], 'Percentage': [90, 80, 95, 75, 95, 75], 'Age': [25, 25, 51, 62, 48, 51]}

In [5]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### 7.	Write a Pandas code to read a CSV and print the top 5 rows

In [7]:
import pandas as pd
pd.read_csv("Employee.data.csv").head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 8.	Create a DataFrame from a Python dictionary.

In [10]:

pd.DataFrame(Education_details)

   Roll no         Name Education  Percentage  Age
0       11      Sanjani       B.E          90   25
1       12   Vigneshwar       B.E          80   25
2       13    Kanimozhi     M.com          95   51
3       14  Arivazhagan   Diploma          75   62
4       15        Priya     B.com          95   48
5       16   Adhikesvan      M.ED          75   51

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [11]:
Employee_details=pd.read_csv("Employee.data.csv")
Employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [12]:
Employee_details["Salary"].mean()

np.float64(62500.0)

In [15]:
Employee_details["Salary"]=Employee_details["Salary"].fillna( value=Employee_details["Salary"].mean() , inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_14620\1444657055.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  Employee_details["Salary"]=Employee_details["Salary"].fillna( value=Employee_details["Salary"].mean() , inplace=True)

In [19]:
Employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [91]:
Employee_details[Employee_details["Age"]>=30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech      NaN  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech      NaN  12-11-2020

## Conceptual Questions